### ISSUE TITLE
Publish cookbook to chef super market

### ISSUE THREAD

**Issue by akash18** [adobe/azure_file#1]
### Expected Behaviour
Release the cookbook when new changes are merged.

### Actual Behaviour
Currently, there is no process to release the cookbook.

**Comment by filmaj** [comment]
OK, for this issue, here's how we're going to do it:

1. I have [Adobe's Chef Supermarket](https://supermarket.chef.io/users/adobe) credentials. I will publish the existing version of this repo as the Adobe user to the Chef Supermarket.
2. @akash18 let me know what your supermarket.chef.io username is and I will add you as collaborator to the published cookbook. I can also add any other Adobe employee that you wish to be added to the cookbook - I'll just need their usernames as well.
3. At this point, you will be able to use your own account's credentials to publish new versions of the cookbook.
4. If at any point you need to modify the list of collaborators, reach out to me or ping the Open Source Office at Adobe (#guild-opensource on Slack or e-mail grp-opensourceoffice@adobe.com).

Let me know how that sounds, @akash18, and I will proceed once I have your blessing.

**Comment by akash18** [comment]
Hi @filmaj ,

Thanks for the update! My username for chef supermarket is `alalwani`. Please initiate the cookbook upload :)

**Comment by filmaj** [comment]
Done! It is live! And you are added as collaborator, from here on out you should be able to upload the cookbook using the `knife cookbook site share` command. For the record, this is the command I ran to upload it:

    knife cookbook site share azure_file "Utilities" -k adobe.pem -o ~src/cookbooks --verbose -u adobe

https://supermarket.chef.io/cookbooks/azure_file
